In [18]:
import requests
from bs4 import BeautifulSoup
import re
import sqlite3
import time
import json

WIKI_BASE = "https://en.wikipedia.org"
URL = "https://en.wikipedia.org/wiki/List_of_highest-grossing_films"
HEADERS = {"User-Agent": "Mozilla/5.0 (educational project)"}

In [3]:
def clean_money(raw: str) -> float | None:
    if not raw:
        return None

    match = re.search(r'\$[\d,]+', raw)
    if not match:
        return None

    num_str = match.group().replace('$', '').replace(',', '')

    try:
        return float(num_str)
    except ValueError:
        return None


def clean_year(raw: str) -> int | None:
    match = re.search(r'(\d{4})', raw)
    return int(match.group(1)) if match else None


def fetch_soup(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, 'html.parser')


def get_director_and_country(film_url: str) -> tuple[str, str]:
    director, country = None, None
    try:
        soup = fetch_soup(WIKI_BASE + film_url)
        infobox = soup.find("table", class_="infobox")
        if not infobox:
            return director, country

        rows = infobox.find_all("tr")
        for row in rows:
            header = row.find("th")
            if not header:
                continue
            label = header.get_text(strip=True).lower()

            if "directed" in label or label == "director":
                td = row.find("td")
                if td:
                    names = [a.get_text(strip=True) for a in td.find_all("a")]
                    if not names:
                        names = [td.get_text(strip=True)]
                    director = ", ".join(names)

            if label in ("country", "countries"):
                td = row.find("td")
                if td:
                    country = td.get_text(" ", strip=True)

    except Exception as e:
        print(f'Could not fetch details from {film_url}: {e}')

    return director, country

In [4]:
soup = fetch_soup(URL)

tables = soup.find_all("table", class_="wikitable")

main_table = None
for tbl in tables:
    first_row_headers = [th.get_text(strip=True) for th in tbl.find_all("th")]
    if "Rank" in first_row_headers and "Title" in first_row_headers:
        main_table = tbl
        break

if main_table is None:
    main_table = tables[0]
    print("Could not locate the expected table; using the first wikitable.")

print("Main table located.")

Main table located.

In [ ]:
films = []

rows = main_table.find_all("tr")[1:]

for row in rows:
    cells = row.find_all(["th", "td"])
    if len(cells) < 4:
        continue

    # --- Title & link -------------------------------------------------
    title_cell = cells[2]                       # 2nd column
    title_tag  = title_cell.find("a")
    title      = title_cell.get_text(strip=True)
    film_link  = title_tag["href"] if title_tag and title_tag.has_attr("href") else None

    # --- Worldwide gross ----------------------------------------------
    gross_raw  = cells[3].get_text(strip=True)
    box_office = clean_money(gross_raw)

    # --- Year ---------------------------------------------------------
    year_raw   = cells[4].get_text(strip=True)
    year       = clean_year(year_raw)

    films.append({
        "title":      title,
        "year":       year,
        "box_office": box_office,
        "link":       film_link,
        "director":   None,
        "country":    None,
    })

print(f"✔ Extracted {len(films)} films from the main table.")

print(films)

✔ Extracted 50 films from the main table.
[{'title': 'Avatar', 'year': 2009, 'box_office': 2923710708.0, 'link': '/wiki/Avatar_(2009_film)', 'director': None, 'country': None}, {'title': 'Avengers: Endgame', 'year': 2019, 'box_office': 2797501328.0, 'link': '/wiki/Avengers:_Endgame', 'director': None, 'country': None}, {'title': 'Avatar: The Way of Water', 'year': 2022, 'box_office': 2334484620.0, 'link': '/wiki/Avatar:_The_Way_of_Water', 'director': None, 'country': None}, {'title': 'Titanic', 'year': 1997, 'box_office': 2257906828.0, 'link': '/wiki/Titanic_(1997_film)', 'director': None, 'country': None}, {'title': 'Ne Zha 2', 'year': 2025, 'box_office': 2215690000.0, 'link': '/wiki/Ne_Zha_2', 'director': None, 'country': None}, {'title': 'Star Wars: The Force Awakens', 'year': 2015, 'box_office': 2068223624.0, 'link': '/wiki/Star_Wars:_The_Force_Awakens', 'director': None, 'country': None}, {'title': 'Avengers: Infinity War', 'year': 2018, 'box_office': 2048359754.0, 'link': '/wiki/Avengers:_Infinity_War', 'director': None, 'country': None}, {'title': 'Spider-Man: No Way Home', 'year': 2021, 'box_office': 1922598800.0, 'link': '/wiki/Spider-Man:_No_Way_Home', 'director': None, 'country': None}, {'title': 'Zootopia 2†', 'year': 2025, 'box_office': 1866578288.0, 'link': '/wiki/Zootopia_2', 'director': None, 'country': None}, {'title': 'Inside Out 2', 'year': 2024, 'box_office': 1698863816.0, 'link': '/wiki/Inside_Out_2', 'director': None, 'country': None}, {'title': 'Jurassic World', 'year': 2015, 'box_office': 1671537444.0, 'link': '/wiki/Jurassic_World', 'director': None, 'country': None}, {'title': 'The Lion King', 'year': 2019, 'box_office': 1656943394.0, 'link': '/wiki/The_Lion_King_(2019_film)', 'director': None, 'country': None}, {'title': 'The Avengers', 'year': 2012, 'box_office': 1518815515.0, 'link': '/wiki/The_Avengers_(2012_film)', 'director': None, 'country': None}, {'title': 'Furious 7', 'year': 2015, 'box_office': 1515341399.0, 'link': '/wiki/Furious_7', 'director': None, 'country': None}, {'title': 'Top Gun: Maverick', 'year': 2022, 'box_office': 1495696292.0, 'link': '/wiki/Top_Gun:_Maverick', 'director': None, 'country': None}, {'title': 'Avatar: Fire and Ash†', 'year': 2025, 'box_office': 1485605263.0, 'link': '/wiki/Avatar:_Fire_and_Ash', 'director': None, 'country': None}, {'title': 'Frozen 2', 'year': 2019, 'box_office': 1450026933.0, 'link': '/wiki/Frozen_2', 'director': None, 'country': None}, {'title': 'Barbie', 'year': 2023, 'box_office': 1447138421.0, 'link': '/wiki/Barbie_(film)', 'director': None, 'country': None}, {'title': 'Avengers: Age of Ultron', 'year': 2015, 'box_office': 1402809540.0, 'link': '/wiki/Avengers:_Age_of_Ultron', 'director': None, 'country': None}, {'title': 'The Super Mario Bros. Movie', 'year': 2023, 'box_office': 1360879735.0, 'link': '/wiki/The_Super_Mario_Bros._Movie', 'director': None, 'country': None}, {'title': 'Black Panther', 'year': 2018, 'box_office': 1347280838.0, 'link': '/wiki/Black_Panther_(film)', 'director': None, 'country': None}, {'title': 'Harry Potter and the Deathly Hallows – Part 2', 'year': 2011, 'box_office': 1342139727.0, 'link': '/wiki/Harry_Potter_and_the_Deathly_Hallows_%E2%80%93_Part_2', 'director': None, 'country': None}, {'title': 'Deadpool & Wolverine', 'year': 2024, 'box_office': 1338073645.0, 'link': '/wiki/Deadpool_%26_Wolverine', 'director': None, 'country': None}, {'title': 'Star Wars: The Last Jedi', 'year': 2017, 'box_office': 1332539889.0, 'link': '/wiki/Star_Wars:_The_Last_Jedi', 'director': None, 'country': None}, {'title': 'Jurassic World: Fallen Kingdom', 'year': 2018, 'box_office': 1308476166.0, 'link': '/wiki/Jurassic_World:_Fallen_Kingdom', 'director': None, 'country': None}, {'title': 'Frozen', 'year': 2013, 'box_office': 1290000000.0, 'link': '/wiki/Frozen_(2013_film)', 'director': None, 'country': None}, {'title': 'Beauty and the Beast', 'year': 2017, 'box_office': 1263521126.0, 'link': '/wiki/Beauty_and_the_Beast_(2017_film)', 'director': None, 'country': None}, {'title': 'Incredibles 2', 'year': 2018, 'box_office': 1242805359.0, 'link': '/wiki/Incredibles_2', 'director': None, 'country': None}, {'title': 'The Fate of the Furious', 'year': 2017, 'box_office': 1238764765.0, 'link': '/wiki/The_Fate_of_the_Furious', 'director': None, 'country': None}, {'title': 'Iron Man 3', 'year': 2013, 'box_office': 1214811252.0, 'link': '/wiki/Iron_Man_3', 'director': None, 'country': None}, {'title': 'Minions', 'year': 2015, 'box_office': 1159444662.0, 'link': '/wiki/Minions_(film)', 'director': None, 'country': None}, {'title': 'Captain America: Civil War', 'year': 2016, 'box_office': 1153337496.0, 'link': '/wiki/Captain_America:_Civil_War', 'director': None, 'country': None}, {'title': 'Aquaman', 'year': 2018, 'box_office': 1148528393.0, 'link': '/wiki/Aquaman_(film)', 'director': None, 'country': None}, {'title': 'The Lord of the Rings: The Return of the King', 'year': 2003, 'box_office': 1147997407.0, 'link': '/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King', 'director': None, 'country': None}, {'title': 'Spider-Man: Far From Home', 'year': 2019, 'box_office': 1132679685.0, 'link': '/wiki/Spider-Man:_Far_From_Home', 'director': None, 'country': None}, {'title': 'Captain Marvel', 'year': 2019, 'box_office': 1128274794.0, 'link': '/wiki/Captain_Marvel_(film)', 'director': None, 'country': None}, {'title': 'Transformers: Dark of the Moon', 'year': 2011, 'box_office': 1123794079.0, 'link': '/wiki/Transformers:_Dark_of_the_Moon', 'director': None, 'country': None}, {'title': 'Skyfall', 'year': 2012, 'box_office': 1108594137.0, 'link': '/wiki/Skyfall', 'director': None, 'country': None}, {'title': 'Transformers: Age of Extinction', 'year': 2014, 'box_office': 1104054072.0, 'link': '/wiki/Transformers:_Age_of_Extinction', 'director': None, 'country': None}, {'title': 'The Dark Knight Rises', 'year': 2012, 'box_office': 1081169825.0, 'link': '/wiki/The_Dark_Knight_Rises', 'director': None, 'country': None}, {'title': 'Joker', 'year': 2019, 'box_office': 1074458282.0, 'link': '/wiki/Joker_(2019_film)', 'director': None, 'country': None}, {'title': 'Star Wars: The Rise of Skywalker', 'year': 2019, 'box_office': 1074144248.0, 'link': '/wiki/Star_Wars:_The_Rise_of_Skywalker', 'director': None, 'country': None}, {'title': 'Toy Story 4', 'year': 2019, 'box_office': 1073394593.0, 'link': '/wiki/Toy_Story_4', 'director': None, 'country': None}, {'title': 'Toy Story 3', 'year': 2010, 'box_office': 1066970811.0, 'link': '/wiki/Toy_Story_3', 'director': None, 'country': None}, {'title': "Pirates of the Caribbean: Dead Man's Chest", 'year': 2006, 'box_office': 1066179747.0, 'link': '/wiki/Pirates_of_the_Caribbean:_Dead_Man%27s_Chest', 'director': None, 'country': None}, {'title': 'Moana 2', 'year': 2024, 'box_office': 1059242164.0, 'link': '/wiki/Moana_2', 'director': None, 'country': None}, {'title': 'Rogue One: A Star Wars Story', 'year': 2016, 'box_office': 1057420387.0, 'link': '/wiki/Rogue_One:_A_Star_Wars_Story', 'director': None, 'country': None}, {'title': 'Aladdin', 'year': 2019, 'box_office': 1050693953.0, 'link': '/wiki/Aladdin_(2019_film)', 'director': None, 'country': None}, {'title': 'Star Wars: Episode I – The Phantom Menace', 'year': 1999, 'box_office': 1046515409.0, 'link': '/wiki/Star_Wars:_Episode_I_%E2%80%93_The_Phantom_Menace', 'director': None, 'country': None}, {'title': 'Pirates of the Caribbean: On Stranger Tides', 'year': 2011, 'box_office': 1045713802.0, 'link': '/wiki/Pirates_of_the_Caribbean:_On_Stranger_Tides', 'director': None, 'country': None}]

In [9]:
for i, film in enumerate(films):
    if film["link"]:
        director, country = get_director_and_country(film["link"])
        film["director"] = director
        film["country"]  = country
        print(f"  [{i+1}/{len(films)}] {film['title']:40s} -> dir: {director}")
        time.sleep(0.5)                         # rate-limit

print("Director/country enrichment complete.")

  [1/50] Avatar                                   -> dir: James Cameron
  [2/50] Avengers: Endgame                        -> dir: Anthony RussoJoe Russo
  [3/50] Avatar: The Way of Water                 -> dir: James Cameron
  [4/50] Titanic                                  -> dir: James Cameron
  [5/50] Ne Zha 2                                 -> dir: Jiaozi
  [6/50] Star Wars: The Force Awakens             -> dir: J. J. Abrams
  [7/50] Avengers: Infinity War                   -> dir: Anthony RussoJoe Russo
  [8/50] Spider-Man: No Way Home                  -> dir: Jon Watts
  [9/50] Zootopia 2†                              -> dir: Jared Bush, Byron Howard
  [10/50] Inside Out 2                             -> dir: Kelsey Mann
  [11/50] Jurassic World                           -> dir: Colin Trevorrow
  [12/50] The Lion King                            -> dir: Jon Favreau
  [13/50] The Avengers                             -> dir: Joss Whedon
  [14/50] Furious 7                                -> dir: James Wan
  [15/50] Top Gun: Maverick                        -> dir: Joseph Kosinski
  [16/50] Avatar: Fire and Ash†                    -> dir: James Cameron
  [17/50] Frozen 2                                 -> dir: Chris Buck, Jennifer Lee
  [18/50] Barbie                                   -> dir: Greta Gerwig
  [19/50] Avengers: Age of Ultron                  -> dir: Joss Whedon
  [20/50] The Super Mario Bros. Movie              -> dir: Aaron Horvath, Michael Jelenic
  [21/50] Black Panther                            -> dir: Ryan Coogler
  [22/50] Harry Potter and the Deathly Hallows – Part 2 -> dir: David Yates
  [23/50] Deadpool & Wolverine                     -> dir: Shawn Levy
  [24/50] Star Wars: The Last Jedi                 -> dir: Rian Johnson
  [25/50] Jurassic World: Fallen Kingdom           -> dir: J. A. Bayona
  [26/50] Frozen                                   -> dir: Chris Buck, Jennifer Lee
  [27/50] Beauty and the Beast                     -> dir: Bill Condon
  [28/50] Incredibles 2                            -> dir: Brad Bird
  [29/50] The Fate of the Furious                  -> dir: F. Gary Gray
  [30/50] Iron Man 3                               -> dir: Shane Black
  [31/50] Minions                                  -> dir: Pierre Coffin, Kyle Balda
  [32/50] Captain America: Civil War               -> dir: Anthony RussoJoe Russo
  [33/50] Aquaman                                  -> dir: James Wan
  [34/50] The Lord of the Rings: The Return of the King -> dir: Peter Jackson
  [35/50] Spider-Man: Far From Home                -> dir: Jon Watts
  [36/50] Captain Marvel                           -> dir: Anna BodenRyan Fleck
  [37/50] Transformers: Dark of the Moon           -> dir: Michael Bay
  [38/50] Skyfall                                  -> dir: Sam Mendes
  [39/50] Transformers: Age of Extinction          -> dir: Michael Bay
  [40/50] The Dark Knight Rises                    -> dir: Christopher Nolan
  [41/50] Joker                                    -> dir: Todd Phillips
  [42/50] Star Wars: The Rise of Skywalker         -> dir: J. J. Abrams
  [43/50] Toy Story 4                              -> dir: Josh Cooley
  [44/50] Toy Story 3                              -> dir: Lee Unkrich
  [45/50] Pirates of the Caribbean: Dead Man's Chest -> dir: Gore Verbinski
  [46/50] Moana 2                                  -> dir: David Derrick Jr.
  [47/50] Rogue One: A Star Wars Story             -> dir: Gareth Edwards
  [48/50] Aladdin                                  -> dir: Guy Ritchie
  [49/50] Star Wars: Episode I – The Phantom Menace -> dir: George Lucas
  [50/50] Pirates of the Caribbean: On Stranger Tides -> dir: Rob Marshall
Director/country enrichment complete.

In [10]:
DB_NAME = "highest_grossing_films.db"

conn = sqlite3.connect(DB_NAME)
cur  = conn.cursor()

cur.execute("DROP TABLE IF EXISTS films;")
cur.execute("""
    CREATE TABLE films (
        id           INTEGER PRIMARY KEY AUTOINCREMENT,
        title        TEXT    NOT NULL,
        release_year INTEGER,
        director     TEXT,
        box_office   REAL,
        country      TEXT
    );
""")

insert_sql = """
    INSERT INTO films (title, release_year, director, box_office, country)
    VALUES (?, ?, ?, ?, ?);
"""
for f in films:
    cur.execute(insert_sql, (
        f["title"],
        f["year"],
        f["director"],
        f["box_office"],
        f["country"],
    ))

conn.commit()
print(f"Inserted {len(films)} rows into '{DB_NAME}'.")

Inserted 50 rows into 'highest_grossing_films.db'.

In [17]:
import pandas as pd


conn =  sqlite3.connect(DB_NAME)
df = pd.read_sql_query("SELECT * FROM films ORDER BY box_office DESC LIMIT 10;", conn)
print("── Top 10 by Box Office ──")
display(df)

# 7b. Count of films per decade
df_decade = pd.read_sql_query("""
    SELECT (release_year / 10) * 10 AS decade,
           COUNT(*)                  AS film_count,
           PRINTF('$%,.0f', AVG(box_office)) AS avg_gross
    FROM   films
    GROUP  BY decade
    ORDER  BY decade;
""", conn)
print("\n── Films per Decade ──")
display(df_decade)

# 7c. Films directed by a specific director (example)
df_dir = pd.read_sql_query("""
    SELECT title, release_year, box_office
    FROM   films
    WHERE  director LIKE '%Cameron%'
    ORDER  BY box_office DESC;
""", conn)
print("\n── Spielberg Films ──")
display(df_dir)

conn.close()
print("Database connection closed.")

── Top 10 by Box Office ──

,id,title,release_year,director,box_office,country
0,1,Avatar,2009,James Cameron,2.923711e+09,United States [ 1 ] [ 3 ] United Kingdom [ 1 ]...
1,2,Avengers: Endgame,2019,Anthony RussoJoe Russo,2.797501e+09,United States
2,3,Avatar: The Way of Water,2022,James Cameron,2.334485e+09,United States
3,4,Titanic,1997,James Cameron,2.257907e+09,United States
4,5,Ne Zha 2,2025,Jiaozi,2.215690e+09,China
5,6,Star Wars: The Force Awakens,2015,J. J. Abrams,2.068224e+09,United States
6,7,Avengers: Infinity War,2018,Anthony RussoJoe Russo,2.048360e+09,United States
7,8,Spider-Man: No Way Home,2021,Jon Watts,1.922599e+09,United States
8,9,Zootopia 2†,2025,"Jared Bush, Byron Howard",1.866578e+09,United States
9,10,Inside Out 2,2024,Kelsey Mann,1.698864e+09,United States

── Films per Decade ──

   decade  film_count    avg_gross
0    1990           2  $1652211119
1    2000           3  $1712629287
2    2010          34  $1332134449
3    2020          11  $1656804640

── Spielberg Films ──

                      title  release_year    box_office
0                    Avatar          2009  2.923711e+09
1  Avatar: The Way of Water          2022  2.334485e+09
2                   Titanic          1997  2.257907e+09
3     Avatar: Fire and Ash†          2025  1.485605e+09

Database connection closed.

In [ ]:
JSON_NAME = "data/films.json"

conn = sqlite3.connect(DB_NAME)
conn.row_factory = sqlite3.Row          # rows behave like dicts
cur = conn.cursor()

cur.execute("""
    SELECT id,
           title,
           release_year,
           director,
           box_office,
           country
    FROM   films
    ORDER  BY box_office DESC;
""")

films = [dict(row) for row in cur.fetchall()]
conn.close()

# Make sure the data/ folder exists
import os
os.makedirs("data", exist_ok=True)

with open(JSON_NAME, "w", encoding="utf-8") as f:
    json.dump(films, f, indent=2, ensure_ascii=False)

print(f"Exported {len(films)} films to {JSON_NAME}")

✔ Exported 50 films to data/films.json